# Generated by Django 5.1.7 on 2025-03-20 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_streak'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='streak',
        ),
    ]
