# Generated by Django 5.1.7 on 2025-03-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('therapist', 'Therapist'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
