# Generated by Django 5.1.7 on 2025-03-21 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_mood_score_medicalprofile_personality_score'),
        ('users', '0005_userprofile_role'),
    ]

    operations = [
    ]
