# Generated by Django 5.1.7 on 2025-03-21 22:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_llm_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activity_level',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_level',
            field=models.CharField(choices=[('seed', 'Seed'), ('sprout', 'Sprout'), ('sapling', 'Sapling'), ('tree', 'Tree'), ('oak', 'Oak'), ('redwood', 'Redwood'), ('forest', 'Forest')], default='seed', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='daily_mood',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='evening_reflection_last_performed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='evening_reflection_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gratitude_journal_last_performed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gratitude_journal_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mindfulness_level',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='morning_meditation_last_performed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='morning_meditation_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='recent_badge',
            field=models.CharField(choices=[('first_step', 'First Step'), ('consistency_champ', 'Consistency Champ'), ('mindful_master', 'Mindful Master'), ('gratitude_guru', 'Gratitude Guru'), ('streak_surfer', 'Streak Surfer'), ('zen_warrior', 'Zen Warrior'), ('wellness_whiz', 'Wellness Whiz'), ('balance_builder', 'Balance Builder'), ('resilience_rockstar', 'Resilience Rockstar'), ('joy_juggler', 'Joy Juggler')], default='first_step', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sleep_quality',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wellness_score',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
