# Generated by Django 5.1.7 on 2025-03-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_activity_level_userprofile_current_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='emotion',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
