# Generated by Django 5.1.7 on 2025-03-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_userprofile_emotion"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalprofile",
            name="suggested_solutions",
            field=models.TextField(blank=True, null=True),
        ),
    ]
