# Generated by Django 5.1.5 on 2025-03-19 18:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Response",
            new_name="Answer",
        ),
    ]
