# Generated by Django 5.1.5 on 2025-03-19 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0002_rename_response_answer"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="users.userprofile",
            ),
        ),
    ]
