# Generated by Django 5.1.5 on 2025-03-19 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0004_alter_answer_question_alter_answer_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="question",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="response",
                to="assessment.question",
            ),
        ),
    ]
