# Generated by Django 5.1.7 on 2025-03-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0007_alter_answer_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="userassessment",
            name="solutions",
            field=models.TextField(blank=True, null=True),
        ),
    ]
