# Generated by Django 5.1.5 on 2025-02-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="room",
            field=models.CharField(max_length=256),
        ),
    ]
