# Generated by Django 5.1.5 on 2025-02-04 13:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_alter_message_room"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Message",
        ),
    ]
