# Generated by Django 5.1.5 on 2025-02-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_room_alter_message_room_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="is_dm",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
