# Generated by Django 5.1.5 on 2025-03-19 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0006_room_is_dm_alter_room_name"),
        ("forum", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="forum",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="forum.forum",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.userprofile"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admin_rooms",
                to="users.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="members",
            field=models.ManyToManyField(related_name="rooms", to="users.userprofile"),
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
