# Generated by Django 5.1.7 on 2025-03-21 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapysession',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'therapist'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='therapysession',
            name='status',
            field=models.CharField(default='Scheduled', max_length=255),
        ),
        migrations.AlterField(
            model_name='therapysession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
